#
# Defines environment variables.
#


# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Vagrant
export VAGRANT_VMWARE_CLONE_DIRECTORY="~/artifacts/vmware"
export VAGRANT_HOME="~/artifacts/vagrant.d"

# Packer
export PACKER_CACHE_DIR="~/artifacts/packer_cache"

# Change default location of Hombrew-Cask symlink location
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Avoid rate limiting while using homebrew
export HOMEBREW_GITHUB_API_TOKEN="token"

# Opt out of google analytics
export HOMEBREW_NO_ANALYTICS=1

# Cookiecutter config location
export COOKIECUTTER_CONFIG=~/dev/cookiecutters/config.yaml
