#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Use direnv
eval "$(direnv hook /use/local/bin/zsh)"

### From homebrew installed zsh-completions
#
# To activate these completions, add the following to your .zshrc:
#
#   fpath=(/usr/local/share/zsh-completions $fpath)
#
# You may also need to force rebuild `zcompdump`:
#
#   rm -f ~/$ZDOTDIR/.zcompdump; compinit
#
# Additionally, if you receive "zsh compinit: insecure directories" warnings
# when attempting to load these completions, you may need to run this:
#
#   chmod go-w /usr/local/share
fpath=(/usr/local/share/zsh-completions $fpath)

alias py='python'
alias i='invoke'
